---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  licence: SIL
#  licence_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: P.J. Onori
  homepage: http://somerandomdude.com/work/iconic/
  email: pj@somerandomdude.com
  twitter: http://twitter.com/somerandomdude
  github: https://github.com/somerandomdude/Iconic
  licence: SIL
  licence_url: http://scripts.sil.org/OFL

  css_prefix: "icon-"
  columns: 4

transform:
  baseline: 0.5
  rescale: 1.2
  offset: -0.05

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: iconic

  fullname: Iconic
  familyname: Iconic

  copyright: Copyright (C) 2012 by P.J. Onori

  ascent: 800
  descent: 200
  weight: Medium


glyphs:

  - file: hash
    code: 0x0023
    #transform: {rescale: 0.5}

  - file: question_mark
    code: 0x003f

  - file: at
    code: 0x0040

  - file: pilcrow
    code: 0x00b6

  - file: info
    code: 0x2139

  - file: arrow_left
    code: 0x2190

  - file: arrow_up
    code: 0x2191

  - file: arrow_right
    code: 0x2192

  - file: arrow_down
    code: 0x2193

  - file: home
    code: 0x2302

  - file: sun_stroke
    code: 0x263c

  - file: sun_fill
    code: 0x2600

  - file: cloud
    code: 0x2601

  - file: umbrella
    code: 0x2602

  - file: star
    code: 0x2605

  - file: moon_stroke
    code: 0x263e

  - file: moon_fill
    code: 0xe07a

  - file: heart_stroke
    code: 0x2661

  - file: heart_fill
    code: 0x2665

  - file: cog
    code: 0x2699

  - file: bolt
    code: 0x26a1

  - file: key_stroke
    code: 0x26bf

  - file: key_fill
    code: 0x1f511

  - file: rain
    code: 0x26c6

  - file: denied
    code: 0x1f6ab

  - file: mail
    code: 0x2709

  - file: pen
    code: 0x270e

  - file: check
    code: 0x2713

  - file: check_alt
    code: 0x2714

  - file: x
    code: 0x2717

  - file: x_alt
    code: 0x2718

  - file: left_quote
    code: 0x275d

  - file: right_quote
    code: 0x275e

  - file: plus
    code: 0x2795

  - file: minus
    code: 0x2796

  - file: curved_arrow
    code: 0x2935

  - file: document_alt_stroke
    code: 0x1f4c4

  - file: document_alt_fill
    code: 0xe080

  - file: calendar
    code: 0x1f4c5

  - file: map_pin_alt
    code: 0xe002

  - file: comment_alt1_stroke
    code: 0xe003

  - file: comment_alt1_fill
    code: 0xe083

  - file: comment_alt2_stroke
    code: 0xe004

  - file: comment_alt2_fill
    code: 0xe084

  - file: pen_alt_stroke
    code: 0xe005

  - file: pen_alt_fill
    code: 0xe085

  - file: pen_alt2
    code: 0xe006

  - file: chat_alt_stroke
    code: 0xe007

  - file: chat_alt_fill
    code: 0xe087

  - file: plus_alt
    code: 0xe008

  - file: minus_alt
    code: 0xe009

  - file: bars_alt
    code: 0xe00a

  - file: book_alt
    code: 0x1f4d4

  - file: aperture_alt
    code: 0xe00c

  - file: beaker_alt
    code: 0xe010

  - file: left_quote_alt
    code: 0xe011

  - file: right_quote_alt
    code: 0xe012

  - file: arrow_left_alt1
    code: 0xe013

  - file: arrow_up_alt1
    code: 0xe014

  - file: arrow_right_alt1
    code: 0xe015

  - file: arrow_down_alt1
    code: 0xe016

  - file: arrow_left_alt2
    code: 0xe017

  - file: arrow_up_alt2
    code: 0xe018

  - file: arrow_right_alt2
    code: 0xe019

  - file: arrow_down_alt2
    code: 0xe01a

  - file: brush
    code: 0xe01b

  - file: brush_alt
    code: 0xe01c

  - file: eyedropper
    code: 0xe01e

  - file: layers
    code: 0xe01f

  - file: layers_alt
    code: 0xe020

  - file: compass
    code: 0xe021

  - file: award_stroke
    code: 0xe022

  - file: award_fill
    code: 0xe0a2

  - file: beaker
    code: 0xe023

  - file: steering_wheel
    code: 0xe024

  - file: eye
    code: 0xe025

  - file: aperture
    code: 0xe026

  - file: image
    code: 0xe027

  - file: chart
    code: 0xe028

  - file: chart_alt
    code: 0xe029

  - file: target
    code: 0x1f3af

  - file: tag_stroke
    code: 0xe02b

  - file: tag_fill
    code: 0xe0ab

  - file: rss
    code: 0xe02c

  - file: rss_alt
    code: 0xe02d

  - file: share
    code: 0xe02e

  - file: undo
    code: 0x21b6

  - file: reload
    code: 0x21bb

  - file: reload_alt
    code: 0xe031

  - file: loop_alt1
    code: 0xe032

  - file: loop_alt2
    code: 0xe033

  - file: loop_alt3
    code: 0xe034

  - file: loop_alt4
    code: 0xe035

  - file: spin
    code: 0xe036

  - file: spin_alt
    code: 0xe037

  - file: move_horizontal
    code: 0xe038

  - file: move_horizontal_alt1
    code: 0xe039

  - file: move_horizontal_alt2
    code: 0xe03a

  - file: move_vertical
    code: 0xe03b

  - file: move_vertical_alt1
    code: 0xe03c

  - file: move_vertical_alt2
    code: 0xe03d

  - file: move
    code: 0xe03e

  - file: move_alt1
    code: 0xe03f

  - file: move_alt2
    code: 0xe040

  - file: transfer
    code: 0xe041

  - file: download
    code: 0xe042

  - file: upload
    code: 0xe043

  - file: cloud_download
    code: 0xe044

  - file: cloud_upload
    code: 0xe045

  - file: fork
    code: 0x2387

  - file: play
    code: 0x25bb

  - file: play_alt
    code: 0xe048

  - file: pause
    code: 0x2389

  - file: stop
    code: 0x25aa

  - file: eject
    code: 0x23cf

  - file: first
    code: 0x23ee

  - file: last
    code: 0x23ed

  - file: fullscreen
    code: 0xe04e

  - file: fullscreen_alt
    code: 0xe04f

  - file: fullscreen_exit
    code: 0xe050

  - file: fullscreen_exit_alt
    code: 0xe051

  - file: equalizer
    code: 0xe052

  - file: article
    code: 0xe053

  - file: read_more
    code: 0xe054

  - file: list
    code: 0xe055

  - file: list_nested
    code: 0xe056

  - file: cursor
    code: 0xe057

  - file: dial
    code: 0xe058

  - file: new_window
    code: 0xe059

  - file: trash_stroke
    code: 0xe05a

  - file: trash_fill
    code: 0xe0da

  - file: battery_half
    code: 0xe05b

  - file: battery_empty
    code: 0xe05c

  - file: battery_charging
    code: 0xe05d

  - file: chat
    code: 0xe05e

  - file: mic
    code: 0x1f3a4

  - file: movie
    code: 0x1f3ac

  - file: headphones
    code: 0x1f3a7

  - file: user
    code: 0x1f464

  - file: lightbulb
    code: 0x1f4a1

  - file: cd
    code: 0x1f4bf

  - file: folder_stroke
    code: 0xe065

  - file: folder_fill
    code: 0xe0e5

  - file: document_stroke
    code: 0x1f4c3

  - file: document_fill
    code: 0xe0e6

  - file: pin
    code: 0x1f4cc

  - file: map_pin_stroke
    code: 0xe068

  - file: map_pin_fill
    code: 0xe0e8

  - file: book
    code: 0x1f4d5

  - file: book_alt2
    code: 0x1f4d6

  - file: box
    code: 0xe06b

  - file: calendar_alt_stroke
    code: 0x1f4c6

  - file: calendar_alt_fill
    code: 0xe0ec

  - file: comment_stroke
    code: 0xe06d

  - file: comment_fill
    code: 0xe0ed

  - file: iphone
    code: 0xe06e

  - file: bars
    code: 0xe06f

  - file: camera
    code: 0x1f4f7

  - file: volume_mute
    code: 0x1f507

  - file: volume
    code: 0x1f50a

  - file: battery_full
    code: 0xe073

  - file: magnifying_glass
    code: 0x1f50e

  - file: lock_stroke
    code: 0xe075

  - file: lock_fill
    code: 0x1f512

  - file: unlock_stroke
    code: 0xe076

  - file: unlock_fill
    code: 0x1f513

  - file: link
    code: 0x1f517

  - file: wrench
    code: 0x1f527

  - file: clock
    code: 0x1f554

  - file: paperclip
    code: 0xe08a

