---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# css-prefix: "icon-"             # prefix for css-generated classes
# demo-columns: 4                 # used for html demo page generation
#
# font:                           # all vars from here will be used as font
#                                 # params in fontforge
#   ...                           # http://fontforge.sourceforge.net/python.html
#
# transform:                      # Transformations applied to the font,
#                                 # order is "resize, offset"
#   resize: 0.68                  # Rescale glyphs around the center of bbox,
#                                 # resize=1 means no scaling
#   offset: -0.1                  # Shift glyphs vertically, positive offset
#                                 # shifts upward, offset=1 means shift upward
#                                 # to (ascent-descent) units
#
# glyphs:
#   - glyph1_file:                # file name, without extention
#       code: 0xNNN               # Symbol code 0x - hex
#       css: icon-gpyph1-name     # For generated CSS
#       search: [word1, word2]    # Search aliases (array). CSS name will be
#                                 # included automatically
#       transform:                # Additional transformation applied to that
#                                 # glyph
#         offset: 0.2
#
################################################################################
#
# Mapping rules:
#
# 1. Downshift 1Fxxx -> Fxxx, because 1Fxxx codes not shown in Chrome/Opera
#


css-prefix: "icon-"
demo-columns: 4

transform:
  resize: 1.3
  offset: -0.05

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: iconic

  fullname: Iconic
  familyname: Iconic

  copyright: Copyright (C) 2012 by Daniel Bruce

  ascent: 1638
  descent: 410
  weight: Medium


glyphs:

  - hash:
      code: 0x0023
      # transform:
      #  resize: 0.5

  - question_mark:
      code: 0x003f

  - at:
      code: 0x0040

  - pilcrow:
      code: 0x00b6

  - info:
      code: 0x2139

  - arrow_left:
      code: 0x2190

  - arrow_up:
      code: 0x2191

  - arrow_right:
      code: 0x2192

  - arrow_down:
      code: 0x2193

  - home:
      code: 0x2302

  - sun_stroke:
      code: 0x263c

  - sun_fill:
      code: 0x2600

  - cloud:
      code: 0x2601

  - umbrella:
      code: 0x2602

  - star:
      code: 0x2605

  - moon_stroke:
      code: 0x263e

  - moon_fill:
      code: 0xe07a

  - heart_stroke:
      code: 0x2661

  - heart_fill:
      code: 0x2665

  - cog:
      code: 0x2699

  - bolt:
      code: 0x26a1

  - key_stroke:
      code: 0x26bf

  - key_fill:
      code: 0x1f511

  - rain:
      code: 0x26c6

  - denied:
      code: 0x1f6ab

  - mail:
      code: 0x2709

  - pen:
      code: 0x270e

  - check:
      code: 0x2713

  - check_alt:
      code: 0x2714

  - x:
      code: 0x2717

  - x_alt:
      code: 0x2718

  - left_quote:
      code: 0x275d

  - right_quote:
      code: 0x275e

  - plus:
      code: 0x2795

  - minus:
      code: 0x2796

  - curved_arrow:
      code: 0x2935

  - document_alt_stroke:
      code: 0x1f4c4

  - document_alt_fill:
      code: 0xe080

  - calendar:
      code: 0x1f4c5

  - map_pin_alt:
      code: 0xe002

  - comment_alt1_stroke:
      code: 0xe003

  - comment_alt1_fill:
      code: 0xe083

  - comment_alt2_stroke:
      code: 0xe004

  - comment_alt2_fill:
      code: 0xe084

  - pen_alt_stroke:
      code: 0xe005

  - pen_alt_fill:
      code: 0xe085

  - pen_alt2:
      code: 0xe006

  - chat_alt_stroke:
      code: 0xe007

  - chat_alt_fill:
      code: 0xe087

  - plus_alt:
      code: 0xe008

  - minus_alt:
      code: 0xe009

  - bars_alt:
      code: 0xe00a

  - book_alt:
      code: 0x1f4d4

  - aperture_alt:
      code: 0xe00c

  - beaker_alt:
      code: 0xe010

  - left_quote_alt:
      code: 0xe011

  - right_quote_alt:
      code: 0xe012

  - arrow_left_alt1:
      code: 0xe013

  - arrow_up_alt1:
      code: 0xe014

  - arrow_right_alt1:
      code: 0xe015

  - arrow_down_alt1:
      code: 0xe016

  - arrow_left_alt2:
      code: 0xe017

  - arrow_up_alt2:
      code: 0xe018

  - arrow_right_alt2:
      code: 0xe019

  - arrow_down_alt2:
      code: 0xe01a

  - brush:
      code: 0xe01b

  - brush_alt:
      code: 0xe01c

  - eyedropper:
      code: 0xe01e

  - layers:
      code: 0xe01f

  - layers_alt:
      code: 0xe020

  - compass:
      code: 0xe021

  - award_stroke:
      code: 0xe022

  - award_fill:
      code: 0xe0a2

  - beaker:
      code: 0xe023

  - steering_wheel:
      code: 0xe024

  - eye:
      code: 0xe025

  - aperture:
      code: 0xe026

  - image:
      code: 0xe027

  - chart:
      code: 0xe028

  - chart_alt:
      code: 0xe029

  - target:
      code: 0x1f3af

  - tag_stroke:
      code: 0xe02b

  - tag_fill:
      code: 0xe0ab

  - rss:
      code: 0xe02c

  - rss_alt:
      code: 0xe02d

  - share:
      code: 0xe02e

  - undo:
      code: 0x21b6

  - reload:
      code: 0x21bb

  - reload_alt:
      code: 0xe031

  - loop_alt1:
      code: 0xe032

  - loop_alt2:
      code: 0xe033

  - loop_alt3:
      code: 0xe034

  - loop_alt4:
      code: 0xe035

  - spin:
      code: 0xe036

  - spin_alt:
      code: 0xe037

  - move_horizontal:
      code: 0xe038

  - move_horizontal_alt1:
      code: 0xe039

  - move_horizontal_alt2:
      code: 0xe03a

  - move_vertical:
      code: 0xe03b

  - move_vertical_alt1:
      code: 0xe03c

  - move_vertical_alt2:
      code: 0xe03d

  - move:
      code: 0xe03e

  - move_alt1:
      code: 0xe03f

  - move_alt2:
      code: 0xe040

  - transfer:
      code: 0xe041

  - download:
      code: 0xe042

  - upload:
      code: 0xe043

  - cloud_download:
      code: 0xe044

  - cloud_upload:
      code: 0xe045

  - fork:
      code: 0x2387

  - play:
      code: 0x25bb

  - play_alt:
      code: 0xe048

  - pause:
      code: 0x2389

  - stop:
      code: 0x25aa

  - eject:
      code: 0x23cf

  - first:
      code: 0x23ee

  - last:
      code: 0x23ed

  - fullscreen:
      code: 0xe04e

  - fullscreen_alt:
      code: 0xe04f

  - fullscreen_exit:
      code: 0xe050

  - fullscreen_exit_alt:
      code: 0xe051

  - equalizer:
      code: 0xe052

  - article:
      code: 0xe053

  - read_more:
      code: 0xe054

  - list:
      code: 0xe055

  - list_nested:
      code: 0xe056

  - cursor:
      code: 0xe057

  - dial:
      code: 0xe058

  - new_window:
      code: 0xe059

  - trash_stroke:
      code: 0xe05a

  - trash_fill:
      code: 0xe0da

  - battery_half:
      code: 0xe05b

  - battery_empty:
      code: 0xe05c

  - battery_charging:
      code: 0xe05d

  - chat:
      code: 0xe05e

  - mic:
      code: 0x1f3a4

  - movie:
      code: 0x1f3ac

  - headphones:
      code: 0x1f3a7

  - user:
      code: 0x1f464

  - lightbulb:
      code: 0x1f4a1

  - cd:
      code: 0x1f4bf

  - folder_stroke:
      code: 0xe065

  - folder_fill:
      code: 0xe0e5

  - document_stroke:
      code: 0x1f4c3

  - document_fill:
      code: 0xe0e6

  - pin:
      code: 0x1f4cc

  - map_pin_stroke:
      code: 0xe068

  - map_pin_fill:
      code: 0xe0e8

  - book:
      code: 0x1f4d5

  - book_alt2:
      code: 0x1f4d6

  - box:
      code: 0xe06b

  - calendar_alt_stroke:
      code: 0x1f4c6

  - calendar_alt_fill:
      code: 0xe0ec

  - comment_stroke:
      code: 0xe06d

  - comment_fill:
      code: 0xe0ed

  - iphone:
      code: 0xe06e

  - bars:
      code: 0xe06f

  - camera:
      code: 0x1f4f7

  - volume_mute:
      code: 0x1f507

  - volume:
      code: 0x1f50a

  - battery_full:
      code: 0xe073

  - magnifying_glass:
      code: 0x1f50e

  - lock_stroke:
      code: 0xe075

  - lock_fill:
      code: 0x1f512

  - unlock_stroke:
      code: 0xe076

  - unlock_fill:
      code: 0x1f513

  - link:
      code: 0x1f517

  - wrench:
      code: 0x1f527

  - clock:
      code: 0x1f554

  - paperclip:
      code: 0xe08a

